#!/usr/bin/env python3
"""
Ciphergy Pipeline — Project Initializer
Creates project scaffolding, registry, sync baseline, and validates integrations.

Usage:
    python scripts/ciphergy_init.py --name "Project Name" --domain custom
    python scripts/ciphergy_init.py --name "My Legal Case" --domain legal
"""

import argparse
import json
import os
import sys
import hashlib
import shutil
from datetime import datetime, timezone

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
DOMAINS = {
    "custom": {
        "description": "Generic project",
        "default_files": [],
        "red_alert_template": "# RED ALERTS\n\nNo alerts at this time.\n\n---\n*Generated by Ciphergy Pipeline*\n",
        "questions_template": "# OPEN QUESTIONS\n\n| # | Question | Priority | Status | Date Asked | Date Answered |\n|---|----------|----------|--------|------------|---------------|\n| 1 | (example) | HIGH | OPEN | {date} | — |\n\n---\n*Generated by Ciphergy Pipeline*\n",
    },
    "legal": {
        "description": "Legal case management",
        "default_files": [
            "_RED_ALERTS.md",
            "_QUESTIONS.md",
            "_TIMELINE.md",
            "_EVIDENCE_INDEX.md",
            "_STRATEGY.md",
        ],
        "red_alert_template": "# RED ALERTS\n\n> Critical issues requiring immediate attention.\n\n| # | Alert | Severity | Status | Date Raised |\n|---|-------|----------|--------|-------------|\n\n---\n*Generated by Ciphergy Pipeline*\n",
        "questions_template": "# OPEN QUESTIONS\n\n| # | Question | Priority | Status | Date Asked | Date Answered |\n|---|----------|----------|--------|------------|---------------|\n\n---\n*Generated by Ciphergy Pipeline*\n",
    },
    "startup": {
        "description": "Startup / product development",
        "default_files": [
            "_RED_ALERTS.md",
            "_QUESTIONS.md",
            "_ROADMAP.md",
            "_METRICS.md",
        ],
        "red_alert_template": "# RED ALERTS\n\n> Blockers and critical issues.\n\n| # | Alert | Impact | Owner | Status |\n|---|-------|--------|-------|--------|\n\n---\n*Generated by Ciphergy Pipeline*\n",
        "questions_template": "# OPEN QUESTIONS\n\n| # | Question | Priority | Status | Date Asked | Date Answered |\n|---|----------|----------|--------|------------|---------------|\n\n---\n*Generated by Ciphergy Pipeline*\n",
    },
    "medical": {
        "description": "Medical case / research",
        "default_files": [
            "_RED_ALERTS.md",
            "_QUESTIONS.md",
            "_PATIENT_TIMELINE.md",
            "_TREATMENT_LOG.md",
        ],
        "red_alert_template": "# RED ALERTS\n\n> Urgent findings and flags.\n\n| # | Alert | Severity | Category | Date |\n|---|-------|----------|----------|------|\n\n---\n*Generated by Ciphergy Pipeline*\n",
        "questions_template": "# OPEN QUESTIONS\n\n| # | Question | Priority | Status | Date Asked | Date Answered |\n|---|----------|----------|--------|------------|---------------|\n\n---\n*Generated by Ciphergy Pipeline*\n",
    },
}


def load_config(config_path):
    """Load and validate ciphergy.yaml config."""
    try:
        import yaml
    except ImportError:
        print("[ERROR] PyYAML is required. Install with: pip install pyyaml")
        sys.exit(1)

    if not os.path.isfile(config_path):
        print(f"[WARN] Config not found at {config_path}")
        print("[INFO] Creating default config...")
        return None

    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    if not config:
        print("[ERROR] Config file is empty or invalid.")
        sys.exit(1)

    return config


def create_default_config(config_path, name, domain):
    """Create a default ciphergy.yaml config file."""
    try:
        import yaml
    except ImportError:
        print("[ERROR] PyYAML is required. Install with: pip install pyyaml")
        sys.exit(1)

    config = {
        "project": {
            "name": name,
            "domain": domain,
            "version": "1.0.0",
            "created": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        },
        "agents": {
            "local": {
                "name": "Local Agent",
                "type": "cli",
                "status": "active",
            },
            "cloud": {
                "name": "Cloud Agent",
                "type": "cloud",
                "status": "idle",
            },
        },
        "asana": {
            "enabled": False,
            "pat_env_var": "ASANA_PAT",
            "workspace_gid": "",
            "project_gid": "",
            "comm_task_gid": "",
        },
        "cascades": {
            "new-evidence": {
                "description": "New data or documents added",
                "priority": 1,
                "steps": ["update_registry", "recompute_hashes", "check_alerts", "sync_check"],
            },
            "answered": {
                "description": "A question has been answered",
                "priority": 2,
                "steps": ["update_questions", "check_cascading_impacts", "sync_check"],
            },
            "phase-change": {
                "description": "Project phase transition",
                "priority": 1,
                "steps": ["update_registry", "recompute_hashes", "full_integrity_check", "sync_check"],
            },
            "deadline": {
                "description": "Deadline approaching or reached",
                "priority": 0,
                "steps": ["check_alerts", "escalate_open_items", "sync_check"],
            },
            "correction": {
                "description": "Error correction in existing data",
                "priority": 1,
                "steps": ["update_registry", "recompute_hashes", "log_correction", "sync_check"],
            },
            "escalation": {
                "description": "Priority escalation",
                "priority": 0,
                "steps": ["update_alerts", "notify_asana", "sync_check"],
            },
        },
        "sync": {
            "auto_push": False,
            "sync_dir": "sync",
            "manifest": "sync/SYNC_MANIFEST.md",
        },
        "dashboard": {
            "port": 5050,
            "auto_refresh_seconds": 30,
        },
    }

    os.makedirs(os.path.dirname(config_path), exist_ok=True)
    with open(config_path, "w") as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)

    print(f"  [OK] Created config: {config_path}")
    return config


def create_registry(registry_path, project_root, name, domain, config):
    """Create .ciphergy/registry.json with file tracking."""
    domain_info = DOMAINS.get(domain, DOMAINS["custom"])

    # Discover existing files to track
    tracked_files = []
    for root, dirs, files in os.walk(project_root):
        # Skip hidden dirs and common excludes
        dirs[:] = [d for d in dirs if not d.startswith(".") and d not in ("node_modules", "__pycache__", "sync")]
        rel_root = os.path.relpath(root, project_root)
        for fname in files:
            if fname.startswith(".") or fname.endswith(".pyc"):
                continue
            rel_path = os.path.join(rel_root, fname) if rel_root != "." else fname
            full_path = os.path.join(root, fname)
            try:
                with open(full_path, "rb") as fh:
                    file_hash = hashlib.md5(fh.read()).hexdigest()
            except (IOError, OSError):
                file_hash = ""

            tracked_files.append({
                "path": rel_path,
                "hash": file_hash,
                "tracked_since": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
                "category": categorize_file(rel_path),
            })

    registry = {
        "project": {
            "name": name,
            "domain": domain,
            "initialized": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        },
        "files": tracked_files,
        "agents": {
            agent_name: {
                "status": agent_info.get("status", "idle"),
                "type": agent_info.get("type", "unknown"),
                "last_active": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            }
            for agent_name, agent_info in config.get("agents", {}).items()
        },
        "sync": {
            "current_version": "v1",
            "last_synced": "never",
            "synced_hashes": {},
        },
        "version_history": [
            {
                "version": "v1",
                "date": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
                "trigger": "initialization",
                "files_changed": len(tracked_files),
            }
        ],
    }

    os.makedirs(os.path.dirname(registry_path), exist_ok=True)
    with open(registry_path, "w") as f:
        json.dump(registry, f, indent=2)

    print(f"  [OK] Created registry: {registry_path} ({len(tracked_files)} files tracked)")
    return registry


def categorize_file(path):
    """Categorize a file by its path/extension."""
    if path.startswith("scripts/"):
        return "script"
    elif path.startswith("docs/"):
        return "documentation"
    elif path.startswith("dashboard/"):
        return "dashboard"
    elif path.startswith("config/"):
        return "configuration"
    elif path.startswith("templates/"):
        return "template"
    elif path.endswith(".md"):
        return "document"
    elif path.endswith(".json"):
        return "data"
    elif path.endswith(".py"):
        return "script"
    elif path.endswith(".sh"):
        return "script"
    else:
        return "other"


def create_sync_baseline(sync_dir, project_root, registry):
    """Create sync/v1/ baseline with all tracked files."""
    v1_dir = os.path.join(sync_dir, "v1")
    os.makedirs(v1_dir, exist_ok=True)

    copied = 0
    for entry in registry.get("files", []):
        fpath = entry.get("path", "")
        src = os.path.join(project_root, fpath)
        if os.path.isfile(src):
            dest = os.path.join(v1_dir, os.path.basename(fpath))
            shutil.copy2(src, dest)
            copied += 1

    print(f"  [OK] Created sync baseline: {v1_dir} ({copied} files)")
    return v1_dir


def create_sync_manifest(manifest_path, registry):
    """Create SYNC_MANIFEST.md."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    file_count = len(registry.get("files", []))

    content = f"""# PROJECT KNOWLEDGE SYNC MANIFEST

## Base: v1 --- {now}

Total files: {file_count}
Current version: v1

## Version Log

| Version | Date | Trigger | Files Changed |
|---------|------|---------|---------------|
| v1 | {now} | Initial build | All files ({file_count}) |

## Instructions

1. Upload the contents of sync/v1/ to your cloud agent project.
2. After upload, run: `ciphergy.sh mark-synced`
3. For subsequent updates, run: `ciphergy.sh project-push`
4. Upload only the new version folder (e.g., sync/v2/).
5. After each upload, run: `ciphergy.sh mark-synced`

## Notes

- Each version folder contains only the files that changed since the last sync.
- The registry tracks hashes to detect changes automatically.
- Never modify files inside sync/v*/ folders directly.

---
*Generated by Ciphergy Pipeline on {now}*
"""

    with open(manifest_path, "w") as f:
        f.write(content)

    print(f"  [OK] Created manifest: {manifest_path}")


def create_templated_files(project_root, domain):
    """Create domain-specific template files."""
    domain_info = DOMAINS.get(domain, DOMAINS["custom"])
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # RED ALERTS
    alerts_path = os.path.join(project_root, "_RED_ALERTS.md")
    template = domain_info["red_alert_template"]
    with open(alerts_path, "w") as f:
        f.write(template)
    print(f"  [OK] Created: _RED_ALERTS.md")

    # QUESTIONS
    questions_path = os.path.join(project_root, "_QUESTIONS.md")
    template = domain_info["questions_template"].replace("{date}", now)
    with open(questions_path, "w") as f:
        f.write(template)
    print(f"  [OK] Created: _QUESTIONS.md")


def validate_asana(config):
    """Test Asana API connection if configured."""
    asana_config = config.get("asana", {})
    if not asana_config.get("enabled", False):
        print("  [SKIP] Asana integration disabled in config.")
        return False

    pat_var = asana_config.get("pat_env_var", "ASANA_PAT")
    pat = os.environ.get(pat_var)
    if not pat:
        print(f"  [WARN] Asana PAT not found in environment variable: {pat_var}")
        print(f"         Set it with: export {pat_var}=your_token")
        return False

    try:
        import urllib.request
        import urllib.error

        req = urllib.request.Request(
            "https://app.asana.com/api/1.0/users/me",
            headers={"Authorization": f"Bearer {pat}"},
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode())
            user_name = data.get("data", {}).get("name", "Unknown")
            print(f"  [OK] Asana connected as: {user_name}")
            return True
    except urllib.error.HTTPError as e:
        print(f"  [ERROR] Asana API returned HTTP {e.code}")
        return False
    except Exception as e:
        print(f"  [ERROR] Asana connection failed: {e}")
        return False


def post_asana_init(config, name):
    """Post initialization message to Asana if connected."""
    asana_config = config.get("asana", {})
    if not asana_config.get("enabled", False):
        return

    task_gid = asana_config.get("comm_task_gid")
    if not task_gid:
        print("  [SKIP] No Asana comm_task_gid configured.")
        return

    pat_var = asana_config.get("pat_env_var", "ASANA_PAT")
    pat = os.environ.get(pat_var)
    if not pat:
        return

    try:
        import urllib.request

        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        message = (
            f"[Ciphergy Pipeline] Project Initialized\n"
            f"Project: {name}\n"
            f"Time: {now}\n"
            f"Status: Ready for first sync"
        )

        payload = json.dumps({"data": {"text": message}}).encode()
        req = urllib.request.Request(
            f"https://app.asana.com/api/1.0/tasks/{task_gid}/stories",
            data=payload,
            headers={
                "Authorization": f"Bearer {pat}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            if resp.status == 201:
                print("  [OK] Asana initialization message posted.")
            else:
                print(f"  [WARN] Asana returned status {resp.status}")
    except Exception as e:
        print(f"  [WARN] Could not post to Asana: {e}")


def main():
    parser = argparse.ArgumentParser(description="Ciphergy Pipeline — Project Initializer")
    parser.add_argument("--name", required=True, help="Project name")
    parser.add_argument("--domain", default="custom", choices=list(DOMAINS.keys()), help="Project domain")
    parser.add_argument("--project-root", default=None, help="Project root directory")
    args = parser.parse_args()

    project_root = args.project_root or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    config_path = os.path.join(project_root, "config", "ciphergy.yaml")
    registry_path = os.path.join(project_root, ".ciphergy", "registry.json")
    sync_dir = os.path.join(project_root, "sync")
    manifest_path = os.path.join(sync_dir, "SYNC_MANIFEST.md")

    print(f"\n  Initializing Ciphergy project: {args.name}")
    print(f"  Domain: {args.domain} ({DOMAINS[args.domain]['description']})")
    print(f"  Root: {project_root}")
    print()

    # Step 1: Config
    config = load_config(config_path)
    if config is None:
        config = create_default_config(config_path, args.name, args.domain)

    # Step 2: Template files
    create_templated_files(project_root, args.domain)

    # Step 3: Registry
    registry = create_registry(registry_path, project_root, args.name, args.domain, config)

    # Step 4: Sync baseline
    os.makedirs(sync_dir, exist_ok=True)
    create_sync_baseline(sync_dir, project_root, registry)

    # Step 5: Manifest
    create_sync_manifest(manifest_path, registry)

    # Step 6: Asana
    print()
    asana_ok = validate_asana(config)
    if asana_ok:
        post_asana_init(config, args.name)

    # Summary
    print()
    print("  " + "=" * 50)
    print(f"  Ciphergy Project Initialized Successfully")
    print("  " + "=" * 50)
    print(f"  Project:    {args.name}")
    print(f"  Domain:     {args.domain}")
    print(f"  Files:      {len(registry.get('files', []))} tracked")
    print(f"  Config:     {config_path}")
    print(f"  Registry:   {registry_path}")
    print(f"  Sync:       {sync_dir}/v1/")
    print(f"  Asana:      {'Connected' if asana_ok else 'Not configured'}")
    print()
    print("  Next steps:")
    print("    1. Review config/ciphergy.yaml and customize settings")
    print("    2. Upload sync/v1/ to your cloud agent")
    print("    3. Run: ciphergy.sh mark-synced")
    print("    4. Run: ciphergy.sh status")
    print()


if __name__ == "__main__":
    main()
