"""SQLAlchemy ORM models for the Legal Knowledge Graph (Aurora PostgreSQL).

These models store the massive, structured legal data siphoned from external
sources (CourtListener, US Code, etc.). They utilize pgvector for semantic
search and "if-then" matching.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from typing import Any

from sqlalchemy import Boolean, Date, DateTime, Float, ForeignKey, Index, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from pgvector.sqlalchemy import Vector

from src.database.engine import Base
from src.database.models import GUID


class Statute(Base):
    """A federal or state statute."""
    __tablename__ = "statutes"

    id: Mapped[uuid.UUID] = mapped_column(GUID(), primary_key=True, default=uuid.uuid4)
    jurisdiction: Mapped[str] = mapped_column(String(50), nullable=False, index=True) # e.g., "federal", "FL", "TX"
    title: Mapped[str] = mapped_column(String(255), nullable=False) # e.g., "Title 8"
    section: Mapped[str] = mapped_column(String(255), nullable=False, index=True) # e.g., "1158"
    heading: Mapped[str] = mapped_column(String(512), nullable=False) # e.g., "Asylum"
    text: Mapped[str] = mapped_column(Text, nullable=False)
    effective_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    
    # Semantic embedding for "if-then" matching (1536 dims for Bedrock Titan/Cohere)
    embedding: Mapped[Any] = mapped_column(Vector(1536), nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    __table_args__ = (
        Index("ix_statutes_embedding", "embedding", postgresql_using="hnsw", postgresql_with={"m": 16, "ef_construction": 64}),
    )


class CaseLaw(Base):
    """A court opinion or ruling."""
    __tablename__ = "case_law"

    id: Mapped[uuid.UUID] = mapped_column(GUID(), primary_key=True, default=uuid.uuid4)
    courtlistener_id: Mapped[int | None] = mapped_column(Integer, unique=True, nullable=True)
    case_name: Mapped[str] = mapped_column(String(1024), nullable=False)
    citation: Mapped[str] = mapped_column(String(255), nullable=False, index=True) # e.g., "347 U.S. 483"
    court: Mapped[str] = mapped_column(String(255), nullable=False, index=True) # e.g., "SCOTUS", "9th Circuit"
    jurisdiction: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    date_filed: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    
    # The actual text of the opinion
    opinion_text: Mapped[str] = mapped_column(Text, nullable=False)
    
    # Extracted holding/summary (generated by LLM during ingestion)
    holding_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    
    # Semantic embedding of the holding/opinion for matching
    embedding: Mapped[Any] = mapped_column(Vector(1536), nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    __table_args__ = (
        Index("ix_case_law_embedding", "embedding", postgresql_using="hnsw", postgresql_with={"m": 16, "ef_construction": 64}),
    )


class CourtRule(Base):
    """Procedural rules (FRCP, local court rules)."""
    __tablename__ = "court_rules"

    id: Mapped[uuid.UUID] = mapped_column(GUID(), primary_key=True, default=uuid.uuid4)
    jurisdiction: Mapped[str] = mapped_column(String(50), nullable=False, index=True)
    rule_set: Mapped[str] = mapped_column(String(255), nullable=False) # e.g., "FRCP", "Florida Rules of Civil Procedure"
    rule_number: Mapped[str] = mapped_column(String(50), nullable=False, index=True) # e.g., "12(b)(6)"
    heading: Mapped[str] = mapped_column(String(512), nullable=False)
    text: Mapped[str] = mapped_column(Text, nullable=False)
    
    # Structured data for the Deadline Sentinel
    deadline_trigger: Mapped[str | None] = mapped_column(String(255), nullable=True) # e.g., "service_of_complaint"
    days_to_respond: Mapped[int | None] = mapped_column(Integer, nullable=True)
    
    embedding: Mapped[Any] = mapped_column(Vector(1536), nullable=True)
    
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
